// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8gEIvHm2eRCqLo4yJQ2QD0afZK7BTZ-M',
    appId: '1:356083679832:web:a781a09132733dc98e402d',
    messagingSenderId: '356083679832',
    projectId: 'noter-e31c3',
    authDomain: 'noter-e31c3.firebaseapp.com',
    databaseURL: 'https://noter-e31c3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'noter-e31c3.appspot.com',
    measurementId: 'G-X0ML3XMJG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPDPLyCnAEkBalox2__OpR7DM12Yl5NM4',
    appId: '1:356083679832:android:30c401de88f916738e402d',
    messagingSenderId: '356083679832',
    projectId: 'noter-e31c3',
    databaseURL: 'https://noter-e31c3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'noter-e31c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa0jU4o-77mJmf97FYB9YUofvaX32Bn64',
    appId: '1:356083679832:ios:d39ddfc4180f893e8e402d',
    messagingSenderId: '356083679832',
    projectId: 'noter-e31c3',
    databaseURL: 'https://noter-e31c3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'noter-e31c3.appspot.com',
    iosBundleId: 'com.example.noter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa0jU4o-77mJmf97FYB9YUofvaX32Bn64',
    appId: '1:356083679832:ios:d39ddfc4180f893e8e402d',
    messagingSenderId: '356083679832',
    projectId: 'noter-e31c3',
    databaseURL: 'https://noter-e31c3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'noter-e31c3.appspot.com',
    iosBundleId: 'com.example.noter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8gEIvHm2eRCqLo4yJQ2QD0afZK7BTZ-M',
    appId: '1:356083679832:web:c06a48158fd910538e402d',
    messagingSenderId: '356083679832',
    projectId: 'noter-e31c3',
    authDomain: 'noter-e31c3.firebaseapp.com',
    databaseURL: 'https://noter-e31c3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'noter-e31c3.appspot.com',
    measurementId: 'G-VBL8F8DNZD',
  );
}
